use_frameworks!

target 'OverlayContainer_Example' do
  pod 'OverlayContainer', :path => '../'
end

target 'OverlayContainer_Tests' do
    pod 'Quick', '~> 1.3'
    pod 'Nimble', '~> 7.3'
    pod 'OverlayContainer', :path => '../'
end
