disabled_rules:
  - 

included:
  - Sources
  - Tests

excluded:
  - Carthage/Checkouts
  - Tests/NimbleTests/XCTestManifests.swift
  - Tests/NimbleTests/Helpers/XCTestCaseProvider.swift

trailing_comma:
  mandatory_comma: true

line_length:
  ignores_comments: true
  ignores_function_declarations: true

identifier_name:
  max_length: 50
  excluded:
    - x
    - l
    - r
    - e
    - n1
    - n2
    - to
  allowed_symbols:
      - _
